apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: web
        image: 164340264957.dkr.ecr.us-east-1.amazonaws.com/assignment:webapp
        ports:
        - containerPort: 8080
