apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: web
        image: <ECR_URI>/webapp:latest
        ports:
        - containerPort: 8080
