apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 164340264957.dkr.ecr.us-east-1.amazonaws.com/assignment:mysql
    ports:
    - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: yourpassword
