apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  namespace: web
  labels:
    app: employees
spec:
  containers:
  - name: web
    image: <ECR_URI>/webapp:latest
    ports:
    - containerPort: 8080
